CREATE TABLE car
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    license_plate_number VARCHAR(255)                             NOT NULL,
    make                 VARCHAR(255)                             NOT NULL,
    model                VARCHAR(255)                             NOT NULL,
    year                 INTEGER                                  NOT NULL,
    current_market_value DECIMAL                                  NOT NULL,
    mileage              DECIMAL                                  NOT NULL,
    car_owner            INTEGER                                  NOT NULL,
    latitude             VARCHAR(255),
    longitude            VARCHAR(255),
    CONSTRAINT pk_car PRIMARY KEY (id)
);

CREATE TABLE car_entry
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    available BOOLEAN                                  NOT NULL,
    car       INTEGER                                  NOT NULL,
    CONSTRAINT pk_carentry PRIMARY KEY (id)
);

ALTER TABLE car
    ADD CONSTRAINT uc_car_license_plate_number UNIQUE (license_plate_number);

ALTER TABLE car_entry
    ADD CONSTRAINT uc_carentry_car UNIQUE (car);

ALTER TABLE car_entry
    ADD CONSTRAINT FK_CARENTRY_ON_CAR FOREIGN KEY (car) REFERENCES car (id);

ALTER TABLE car
    ADD CONSTRAINT FK_CAR_ON_CAR_OWNER FOREIGN KEY (car_owner) REFERENCES car_owner (id);