CREATE TABLE employee
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                             NOT NULL,
    password VARCHAR(255)                             NOT NULL,
    name     VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_username UNIQUE (username);