CREATE TABLE car_rent
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    car_id           INTEGER,
    rent_start_time  TIMESTAMP WITHOUT TIME ZONE,
    rent_finish_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_car_rent PRIMARY KEY (id)
);

ALTER TABLE car_rent
    ADD CONSTRAINT FK_CAR_RENT_ON_CAR FOREIGN KEY (car_id) REFERENCES car (id);