name: Test

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/stackeduary/adilsdeals-api
  HOST: 52.214.106.12
  USERNAME: ec2-user

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE }}:latest
          push: true

      - name: Update docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ HOST }}
          username: ${{ USERNAME }}
          key: ${{ secrets.KEY }}
          source: docker-compose.yml
          target: "~"
          overwrite: true

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ HOST }}
          username: ${{ USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker-compose pull
            docker-compose up -d

      - name: Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ HOST }}
          username: ${{ USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker image prune -a -f
            docker system prune -f --volumes
