name: Deploy to Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Deploy backend to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      run: |
        git remote add heroku-backend https://heroku:$HEROKU_API_TOKEN@git.heroku.com/adilsdealsapi.git
        git subtree push --prefix backend heroku-backend main

    - name: Deploy frontend to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      run: |
        git remote add heroku-frontend https://heroku:$HEROKU_API_TOKEN@git.heroku.com/adilsdeals.git
        git subtree push --prefix frontend heroku-frontend main
